# ~/.config/starship.toml

# Use custom format
#format = "$all"

format = """
[┌─────|](bold #44475a) $battery$username$localip$memory_usage$status$cmd_duration $shell
[│](bold #44475a) $directory$git_state$rust$package$java$lua$python
[└─$sudo❯](bold #44475a) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false


[battery]
charging_symbol = "↑"
discharging_symbol = "↓"
disabled = false


[[battery.display]]
threshold = 10
style = "bold #ff5555"


[[battery.display]]
threshold = 50
style = "bold #f1fa8c" 


[[battery.display]]
threshold = 100
style = "bold #ff5555" 


[localip]
ssh_only = false
format = "@[$localipv4](bold #ff79c6)"
disabled = false


[sudo]
allow_windows = true
disabled = false
symbol = "S"
format = "$symbol"


[memory_usage]
disabled = false
threshold = -1
style = "#50fa7b"
symbol = ""
format = " [${ram}]($style) "


[username]
style_user = "#bd93f9 bold"
style_root = "#ff5555 bold"
format = "[$user]($style)"
disabled = false
show_always = true


[status]
style = "bg:#ff5555"
symbol = ""
success_symbol = ""
not_executable_symbol = "Not exe"
not_found_symbol = "Not found"
format = '[$symbol $common_meaning Error Code: $status]($style) '
map_symbol = true
disabled = false


[cmd_duration]
min_time = 0
format = "[$duration](bold #ffb86c)"


[shell]
style = "#bd93f9"
disabled = false


[directory]
style = "#bd93f9"


